import { QuizSection, Question, QuestionType } from './types';

export const QUESTIONS: Question[] = [
  // ==========================================
  // Part 1 (Questions 1-83)
  // ==========================================
  { id: 'q1', text: '心理咨询师与求助者之间的距离属于（ ）。', options: ['A. 公众', 'B. 个人', 'C. 社交', 'D. 亲密'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q2', text: '“男女搭配，干活不累”，这是一种（ ）现象。', options: ['A. 社会助长', 'B. 社会自由', 'C. 社会强化', 'D. 社会抑制'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q3', text: '目光是最能准确反映人的内心状况的身体语言形式。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q4', text: '婴儿出生一两天后就有笑的反应，这属于（ ）。', options: ['A. 有选择的社会性微笑', 'B. 自发性微笑', 'C. 无选择的社会性微笑', 'D. 条件反射的笑'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q5', text: '在吃“大锅饭”的单位，最容易产生的现象是（ ）。', options: ['A. 社会促进', 'B. 社会抑制', 'C. 平衡理论', 'D. 社会懈怠'], correctAnswer: 'D', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q6', text: '倾听时容易出现的错误包括（ ）。', options: ['A. 不做道德性判断', 'B. 急于下结论', 'C. 轻视求助者问题', 'D. 转移求助者话题'], correctAnswer: ['B', 'C', 'D'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q7', text: '以下属于违背心理咨询伦理的行为是（ ）。', options: ['A. 咨询过程中记录', 'B. 询问婚姻状况', 'C. 未经同意录音', 'D. 难以胜任时转介'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q8', text: '一般单一性压力对人不一定是有害的。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q9', text: '人际吸引最强烈的形式是（ ）。', options: ['A. 亲情', 'B. 友情', 'C. 爱情', 'D. 喜欢'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q10', text: '首因效应在人际知觉中起到了重要作用。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q11', text: '科学心理学的创始人是（ ）。', options: ['A. 詹姆斯', 'B. 艾宾浩斯', 'C. 冯特', 'D. 弗洛伊德'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q12', text: '躯体感觉中枢位于（ ）。', options: ['A. 额叶', 'B. 颞叶', 'C. 枕叶', 'D. 顶叶'], correctAnswer: 'D', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q13', text: '詹姆士的自尊公式是（ ）。', options: ['A. 成功/自信', 'B. 成功/抱负', 'C. 自信/抱负', 'D. 抱负/成功'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q14', text: '态度转换的Dissonance理论是由（ ）提出的。', options: ['A. 海德', 'B. 费斯廷格', 'C. 奥斯古德', 'D. 凯利'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q15', text: '舒茨提出的三维人际关系理论，人有三种基本人际需要。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q16', text: '“情人眼里出西施”是一种（ ）。', options: ['A. 刻板印象', 'B. 光环效应', 'C. 首因效应', 'D. 近因效应'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q17', text: '印象管理是个体适应社会生活的一种方式。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q18', text: '态度的三个成分不包括（ ）。', options: ['A. 认知', 'B. 情感', 'C. 行为倾向', 'D. 意志'], correctAnswer: 'D', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q19', text: '影响从众的因素包括（ ）。', options: ['A. 群体一致性', 'B. 群体规模', 'C. 个体人格', 'D. 性别差异'], correctAnswer: ['A', 'B', 'C'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q20', text: '社会交换论的创始人是（ ）。', options: ['A. 霍曼斯', 'B. 班杜拉', 'C. 米德', 'D. 弗洛姆'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q21', text: '神经系统的基本单位是（ ）。', options: ['A. 突触', 'B. 神经元', 'C. 神经胶质', 'D. 轴突'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q22', text: '注意的两个基本特征是（ ）。', options: ['A. 指向性', 'B. 集中性', 'C. 稳定性', 'D. 动态性'], correctAnswer: ['A', 'B'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q23', text: '感受性与感觉阈限成（ ）关系。', options: ['A. 正比', 'B. 反比', 'C. 指数', 'D. 无关'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q24', text: '知觉的特性不包括（ ）。', options: ['A. 整体性', 'B. 选择性', 'C. 恒常性', 'D. 变动性'], correctAnswer: 'D', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q25', text: '瞬时记忆的容量很大。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q26', text: '短时记忆的容量一般为（ ）个单位。', options: ['A. 5-9', 'B. 3-5', 'C. 10-15', 'D. 无限'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q27', text: '思维的本质特征是（ ）。', options: ['A. 形象性', 'B. 概括性', 'C. 间接性', 'D. 直接性'], correctAnswer: ['B', 'C'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q28', text: '表情包括（ ）。', options: ['A. 面部表情', 'B. 言语表情', 'C. 姿态表情', 'D. 内心表情'], correctAnswer: ['A', 'B', 'C'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q29', text: '动机产生的内在条件是（ ）。', options: ['A. 诱因', 'B. 兴趣', 'C. 需要', 'D. 信念'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q30', text: '意志的品质包括（ ）。', options: ['A. 自觉性', 'B. 果断性', 'C. 坚韧性', 'D. 自制性'], correctAnswer: ['A', 'B', 'C', 'D'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q31', text: '能力是顺利完成某种活动所必须具备的心理特征。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q32', text: '希波克拉底将气质分为四种类型。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q33', text: '巴甫洛夫认为高级神经活动的基本过程是兴奋和抑制。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q34', text: '人格的特征包括（ ）。', options: ['A. 独特性', 'B. 稳定性', 'C. 统整性', 'D. 功能性'], correctAnswer: ['A', 'B', 'C', 'D'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q35', text: '投射测验的代表是（ ）。', options: ['A. MMPI', 'B. 罗夏墨迹测验', 'C. EPQ', 'D. 16PF'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q36', text: '心理咨询师与求助者之间的距离属于（ ）。（重复真题）', options: ['A. 公众', 'B. 个人', 'C. 社交', 'D. 亲密'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q37', text: '“男女搭配，干活不累”，这是一种（ ）现象。（重复真题）', options: ['A. 社会助长', 'B. 社会自由', 'C. 社会强化', 'D. 社会抑制'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q38', text: '家庭是社会化的载体。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q39', text: '咨询关系中需要明确求助者的权利包括（ ）。', options: ['A. 遵守职业道德', 'B. 提供真实的资料', 'C. 提出中止咨询', 'D. 完成作业'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q40', text: '真诚不等于说实话。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q41', text: '以下属于双重关系的是（ ）。', options: ['A. 为学生咨询', 'B. 转介', 'C. 网络了解', 'D. 面询'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q42', text: '情感反应最有效的方式是针对求助者（ ）的情感。', options: ['A. 现在的', 'B. 过去的', 'C. 未来的', 'D. 潜意识的'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q43', text: '咨询师不思进取违背了善行原则。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q44', text: '人际吸引最强烈形式是爱情。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q45', text: '心理正常与不正常是绝对对立的。', correctAnswer: 'False', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q46', text: '针对正常人发展问题的咨询是发展性咨询。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q47', text: '咨询中必须建立良好关系。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q48', text: '保密原则是第一原则。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q49', text: '首因效应很重要。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q50', text: '感觉后像分为正后像和负后像。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q51', text: '深度知觉是空间知觉的一种。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q52', text: '自变量是研究者控制的。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q53', text: '相关不等于因果。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q54', text: '双盲实验控制实验者效应。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q55', text: '条件反射包括经典和操作。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q56', text: '负强化减少厌恶刺激。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q57', text: '评估包括观察、访谈、测验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q58', text: '咨询不包含给人生建议。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q59', text: '反社会人格特点是不顾规则。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q60', text: '去中心化是具体运算特征。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q61', text: '观察学习是班杜拉提出的。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q62', text: '最高层是自我实现。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q63', text: '气质类型不分好坏。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q64', text: '情绪功能包括信号功能。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q65', text: '思维过程包括分析综合。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q66', text: '遗忘曲线是艾宾浩斯。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q67', text: '一朝被蛇咬是情绪记忆。', options: ['A. 形象', 'B. 逻辑', 'C. 情绪', 'D. 动作'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q68', text: '大脑皮层的主管听觉区在（ ）。', options: ['A. 额叶', 'B. 颞叶', 'C. 枕叶', 'D. 顶叶'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q69', text: '大脑皮层的主管视觉区在（ ）。', options: ['A. 额叶', 'B. 颞叶', 'C. 枕叶', 'D. 顶叶'], correctAnswer: 'C', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q70', text: '威尔尼克区受损会引起（ ）。', options: ['A. 表达失语', 'B. 接受失语', 'C. 视觉失语', 'D. 书写失语'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q71', text: '布洛卡区受损会引起（ ）。', options: ['A. 表达失语', 'B. 接受失语', 'C. 视觉失语', 'D. 书写失语'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q72', text: '神经元之间信息传递是通过（ ）完成的。', options: ['A. 树突', 'B. 轴突', 'C. 细胞体', 'D. 突触'], correctAnswer: 'D', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q73', text: '网状结构对于维持意识水平有重要作用。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q74', text: '植物性神经系统包括交感神经和副交感神经。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q75', text: '感受性高低用感觉阈限衡量。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q76', text: '由于刺激物持续作用引起的感受性变化叫（ ）。', options: ['A. 适应', 'B. 对比', 'C. 后像', 'D. 联觉'], correctAnswer: 'A', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q77', text: '红花衬在绿叶上显得更红是（ ）。', options: ['A. 继时对比', 'B. 同时对比', 'C. 感觉补偿', 'D. 感觉后像'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q78', text: '看见红颜色感觉温暖是联觉。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q79', text: '深度知觉双眼线索包括（ ）。', options: ['A. 双眼视差', 'B. 辐合', 'C. 遮挡', 'D. 线条透视'], correctAnswer: ['A', 'B'], type: QuestionType.Multi, section: QuizSection.Part1 },
  { id: 'q80', text: '运动知觉包括真动、似动、诱导运动、运动后效。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q81', text: '注意分配的条件是其中一项非常熟练。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },
  { id: 'q82', text: '长时记忆容量（ ）。', options: ['A. 5-9', 'B. 无限', 'C. 极大', 'D. 较小'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part1 },
  { id: 'q83', text: '表象具有形象性和概括性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part1 },

  // ==========================================
  // Part 2 (Questions 84-166)
  // ==========================================
  { id: 'q84', text: '遗忘的进程通常是（ ）。（重复）', options: ['A. 先慢后快', 'B. 先快后慢', 'C. 倒 U 型曲线', 'D. U 型曲线'], correctAnswer: 'B', type: QuestionType.Single, section: QuizSection.Part2 },
  { id: 'q85', text: '“狐狸吃不着葡萄，就说葡萄是酸的”是（ ）防御机制。', options: ['A. 投射', 'B. 升华', 'C. 转移', 'D. 合理化'], correctAnswer: 'D', type: QuestionType.Single, section: QuizSection.Part2 },
  { id: 'q86', text: '皮亚杰认为心理起源于动作。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q87', text: '精神分析认为本我的活动原则是快乐原则。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q88', text: '合理情绪疗法 ABC 理论中 B 代表信念。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q89', text: '强迫性人格障碍特征是过分完美。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q90', text: '埃里克森青年期任务是建立同一性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q91', text: '病理性错觉特点是不能接受现实检验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q92', text: '角色失败指不得不退出舞台。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q93', text: '形式运算阶段儿童有抽象逻辑思维。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q94', text: '弗洛伊德发展阶段包括口欲期等。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q95', text: '维果茨基提出最近发展区。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q96', text: '婴儿深度知觉出现在 6 个月。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q97', text: '第二反抗期特征包括独立感。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q98', text: '幻觉是指无对象感觉。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q99', text: '强迫观念违背本人意愿。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q100', text: '适应障碍病程不超过半年。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q101', text: '咨询关系是职业关系。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q102', text: '共情是体验他人内心。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q103', text: '效果评估包括求助者自评等。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q104', text: '认知领悟疗法创始人钟友彬。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q105', text: '压力源分三类。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q106', text: '惊吓期是灾难综合征阶段。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q107', text: '制定目标是咨询基本阶段。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q108', text: '发展常模是常模分数类型。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q109', text: '信度指一致性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q110', text: '效度指准确性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q111', text: 'WAIS-RC 包含 11 个测验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q112', text: '瑞文测验非言语。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q113', text: '保密例外包含致命威胁。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q114', text: '咨询对象是心理不健康者。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q115', text: '识别自动想法是贝克技术。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q116', text: '神经症门诊多。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q117', text: '操作智商 PIQ。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q118', text: '测验标准化含评分。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q119', text: '样本同质性重要。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q120', text: 'P 近 0.5 区分度高。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q121', text: '效度受误差影响。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q122', text: 'EPQ 的 P 代表精神质。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q123', text: '布洛卡受损引起表达失语。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q124', text: '气质主要受遗传影响。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q125', text: '性格表现品德。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q126', text: '感受性与阈限反比。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q127', text: '梦在快速眼动期。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q128', text: '催眠不是睡眠。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q129', text: '心理冲突有常形变形。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q130', text: '色盲受 X 遗传。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q131', text: '广泛焦虑持续担忧。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q132', text: '心理物理学费希纳。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q133', text: '分层抽样代表性好。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q134', text: 'P<0.05 显著。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q135', text: '皮尔逊适用于线性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q136', text: '正态分布钟形。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q137', text: '标准差反映离散。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q138', text: '比内测验最早。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q139', text: '背数是言语分测验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q140', text: '离差智商反映位置。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q141', text: 'SCL-90 因子分。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q142', text: '尊重真诚共情。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q143', text: '助人自助。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q144', text: '转介。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q145', text: '正负移情。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q146', text: '求助者中心罗杰斯。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q147', text: '空椅子。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q148', text: '暴露疗法。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q149', text: '适应障碍半年。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q150', text: '咨询伦理 5 原则。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q151', text: 'MMPI 重复题 16。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q152', text: '16PF 维度 16。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q153', text: 'EPQ 含 L 量表。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q154', text: 'SCL-90 项目 90。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q155', text: 'SAS 20 项。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q156', text: 'SDS 20 项。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q157', text: 'CRT 瑞文修订版。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q158', text: 'WISC 测验儿童。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q159', text: 'CBCL 评定行为。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q160', text: 'BPRS 评定精神病。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q161', text: 'HAMA 评定焦虑。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q162', text: 'HAMD 评定抑郁。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q163', text: '生活事件量表 LES。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q164', text: '应对方式问卷 CSQ。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q165', text: '艾森克人格 EPQ。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },
  { id: 'q166', text: '卡特尔 16PF。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part2 },

  // ==========================================
  // Part 3 (Questions 167-250)
  // ==========================================
  { id: 'q167', text: 'SCL-90 总分超过 160 为阳性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q168', text: 'MMPI 399 版 Q 量表 22 无效。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q169', text: 'EPQ E < 38.5 内向。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q170', text: 'SAS 60-69 中度。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q171', text: 'SDS 反向项目 10 个。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q172', text: 'Pt 是精神衰弱。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q173', text: '视觉性言语中枢角回。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q174', text: '控制点理论罗特。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q175', text: 'CBT 改变认知。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q176', text: '常模分数类型含发展常模。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q177', text: '信度一致性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q178', text: '效度准确性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q179', text: 'WAIS-RC 11 分测验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q180', text: '瑞文非言语。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q181', text: '中国修订瑞文 CRT。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q182', text: '伦理原则不含权威。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q183', text: '保密例外含传染病威胁。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q184', text: '咨询对象心理不健康者。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q185', text: '去中心化贝克技术。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q186', text: '神经症门诊多。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q187', text: '操作智商 PIQ。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q188', text: '测验标准化含解释。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q189', text: '样本同质性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q190', text: 'P 越近 0.5 区分度好。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q191', text: '气质遗传决定。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q192', text: '性格表现品德。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q193', text: '感受性反比。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q194', text: '一朝被蛇咬情绪记忆。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q195', text: '遗忘曲线先快后慢。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q196', text: '思维本质概括性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q197', text: '情绪适应功能。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q198', text: '马斯洛自我实现。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q199', text: '班杜拉观察学习。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q200', text: '形式运算逻辑。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q201', text: '幻觉无对象。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q202', text: '强迫观念违背意愿。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q203', text: '适应障碍半年。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q204', text: '共情体验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q205', text: '钟友彬。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q206', text: '三类压力源。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q207', text: '惊吓期。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q208', text: '四大阶段。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q209', text: '160 阳性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q210', text: 'Q 22 无效。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q211', text: 'E < 38.5。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q212', text: '60-69 中度。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q213', text: '反向 10。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q214', text: 'Pt 精神衰弱。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q215', text: '角回。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q216', text: '控制点罗特。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q217', text: 'CBT 改变认知。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q218', text: '信度一致性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q219', text: '效度准确性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q220', text: '瑞文非言语。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q221', text: '不含权威。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q222', text: '心理不健康者。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q223', text: '神经症门诊多。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q224', text: 'PIQ。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q225', text: '同质性。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q226', text: 'P 0.5。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q227', text: '遗传决定。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q228', text: '表现品德。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q229', text: '助人自助。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q230', text: '离差智商。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q231', text: '比内最早。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q232', text: '标准差离散。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q233', text: '正态分布。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q234', text: '显著水平。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q235', text: '相关不因果。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q236', text: '自变量控制。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q237', text: '双盲实验。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q238', text: '经典条件。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q239', text: '负强化。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q240', text: '评估访谈。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q241', text: '自我实现。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q242', text: '班杜拉。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q243', text: '皮亚杰。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q244', text: '埃里克森。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q245', text: '弗洛伊德。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q246', text: '罗杰斯。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q247', text: '艾利斯。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q248', text: '贝克。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q249', text: '冯特创始人。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
  { id: 'q250', text: '詹姆斯公式。', correctAnswer: 'True', type: QuestionType.TrueFalse, section: QuizSection.Part3 },
];
